### ISSUE TITLE
Invalid extension

### ISSUE THREAD

**Issue by salenka** [wrCisco/SigilPlugin_cssUndefinedClasses#1]
When I select the zip file on the Sigil Preferences window, it shows an error message saying that the extension format is invalid.

I am using Windows 10 Home edition.

![Sigil plugin error](https://user-images.githubusercontent.com/64967329/205127448-42ce9c0e-adcb-4bd4-b3ab-2b5f531d7800.png)

**Comment by wrCisco** [comment]
Can you show me the zip file you are trying to add to Sigil? The version 0.2.2 of this plugin has been downloaded over 1000 times on https://www.mobileread.com/forums/showthread.php?t=332317 and it never gave this problem.

**Comment by salenka** [comment]
> Can you show me the zip file you are trying to add to Sigil? The version 0.2.2 of this plugin has been downloaded over 1000 times on https://www.mobileread.com/forums/showthread.php?t=332317 and it never gave this problem.

Sure...
[SigilPlugin_cssUndefinedClasses-master.zip](https://github.com/wrCisco/SigilPlugin_cssUndefinedClasses/files/10135871/SigilPlugin_cssUndefinedClasses-master.zip)

I have downloaded it from here, a couple hours ago.

**Comment by wrCisco** [comment]
Yeah, you can find the releases of the plugin that work out-of-the-box on the releases pages here on github (https://github.com/wrCisco/SigilPlugin_cssUndefinedClasses/releases) or in the plugin page on mobileread.
The entire repository that you downloaded the first time can be useful if you want to dabble in the code or if you want to rebuild the plugin yourself for some reason.
Glad the issue is solved.
